language: android
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-26
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- echo TEST
- ls
- echo TEST
- mv analytics.xml app/src/free/res/xml/analytics.xml
- mv ads.xml app/src/free/res/values/ads.xml
- mv secrets.xml app/src/main/res/values/secrets.xml
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
script:
- "./gradlew clean test"
env:
  global:
    secure: Z62ZbwgXnu+U99fY3NKkZfy2AMITDdYBVZLMxrW683UNm5bbh0ZQFGjiDXiybjVlDLVZZq9b+DAUpUnZtVECfzQqvLS0AhK8J0G7ZL/x7qDvZOFyYDcmfyM7o2Xwz9sj8PeTZi8O/cdYfbPNe3mX+sugUt3m1VEsp/wEZ9IOVVgxqU8TUxit/9fEusx6+1NSVc6BKAuIWhCTucKS3TSpFXlZiJh8VRHQJx1Ree/b8FXfDM0pRfm8WZQBn2RU+9EYjqV/3G+/kQvskbmveYFLFUd4hwG0k/IlRhGtNUCjtUXNQi+sr/m1DEjxIxNOgkzNYVllqaMVCje9ks32rIPSNNwB7JNgxOYi5ut6HbWeZjQ0MYhmfs5c9MelA8ZckAHxkBuaZfD9lfRujOf2N49D1ohmLtAVQH5Lr9hr4Y56HytF39sF7hUYT1hyvhwdfG7/ol/a/VyCirJsfiSUdpHnQuHnJyodWJxPxo0edXIu468KteEv4cdzjkhRh9IaTVNv9MQwtTFjnQhQu4Xb7R0aIIZCNMBMfamNAni4jhu5TyKufi3acHvhMPmtFtkP8NuGymDgSZKJhdv1JcF6d5yqkAjiJRyKYPGL/+KkvzUcfRy0iMbsNTxA1OKTIN5u16tpE9208sAVwaPKzT26L68kIbDM4ZjLqIEHhWnxIvVQlLE=
