language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-27.0.3
    - android-26
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - echo "<?xml version="1.0" encoding="utf-8"?>\n<resources>\n    <string name="exchange_rate_key" translatable="false">SAMPLE_KEY</string>\n    <string name="classicAdUnitId">SAMPLE_ID</string>\n</resources>" >> app/src/main/res/values/secrets.xml
  - echo "<?xml version="1.0" encoding="utf-8"?>\n<resources>\n</resources>" >> app/src/main/res/xml/analytics.xml
script:
   - ./gradlew clean test