language: android
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-26
before_install:
- openssl aes-256-cbc -K $encrypted_f86bd80ecf4c_key -iv $encrypted_f86bd80ecf4c_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
script:
- "./gradlew clean test"
